{
 "title": "Futuristic Linux Host Dashboard",
 "description": "Monitor Linux host (VM, Server, OS), your personal machines with a futuristic dashboard.",
 "tags": [
  "Node",
  "Prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "release",
    "label": "Kernel Version",
    "query": "label_values(node_uname_info{instance=~\"$node\"}, release)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info{instance=~\"$node\"}, job)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_uname_info{instance=~\"$node\"}, instance)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(node_uname_info{instance=~\"$node\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Battery",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_power_supply_capacity{instance=~\"$node\"}",
     "legendFormat": "Battery percentage"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Disk I/O Busy",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance, device) (irate(node_disk_io_time_seconds_total{job=\"$job\",instance=\"$node\",device=~\"$device\"}[5m])) * 100) / count(node_disk_io_time_seconds_total{job=\"$job\",instance=\"$node\",device=~\"$device\"})"
    }
   ]
  },
  {
   "title": "Disk Space Used (Root)",
   "type": "gauge",
   "description": "Space Used On Root Mount",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"$job\",instance=\"$node\",device=~\"$device\",fstype=~\"$fstype\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{job=\"$job\",instance=\"$node\",device=~\"$device\",fstype=~\"$fstype\",mountpoint=\"/\"})"
    }
   ]
  }
 ]
}